name: boleto_mask
description: makes easy to masks boletos barcodes.
version: 0.0.1
repository: 'https://github.com/swipetech/boletoMask'

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  mask_text_input_formatter: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
